---
services:
  db:
    image: postgres:15-alpine
    container_name: thunder-buddy-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localdev
      DB_PASSWORD: localdev
    ports:
      - "5432:5432"
    volumes:
      - thunder_buddy_postgres_15:/var/lib/postgresql/data
      - ./scripts/db/init:/docker-entrypoint-initdb.d
    networks:
      - thunder-buddy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thunderbuddy -d thunderbuddy"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: aasimsyed/thunder-buddy:latest
    platform: linux/arm64
    container_name: thunder-buddy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://thunderbuddy:localdev@db:5432/thunderbuddy
      DB_PASSWORD: localdev
      DOCKER_USERNAME: aasimsyed
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - thunder-buddy-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  thunder_buddy_postgres_15:
    name: thunder_buddy_postgres_15

networks:
  thunder-buddy-network:
    name: thunder-buddy-network
