---
services:
  db:
    image: postgres:15-alpine
    container_name: thunder-buddy-db
    env_file:
      - ${ENV_FILE:-.env.local}
    environment:
      POSTGRES_DB: postgres # Default database
      POSTGRES_USER: postgres # Default superuser
      POSTGRES_PASSWORD: localdev
    ports:
      - "5432:5432"
    volumes:
      - thunder_buddy_postgres_15:/var/lib/postgresql/data
      - ./scripts/db/init:/docker-entrypoint-initdb.d # Init scripts
    networks:
      - thunder-buddy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thunderbuddy -d thunderbuddy"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: thunder-buddy:latest
    container_name: thunder-buddy
    env_file:
      - ${ENV_FILE:-.env.local}
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://thunderbuddy:localdev@db:5432/thunderbuddy
      - DB_PASSWORD=localdev
    depends_on:
      db:
        condition: service_healthy
    networks:
      - thunder-buddy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  thunder_buddy_postgres_15:
    name: thunder_buddy_postgres_15

networks:
  thunder-buddy-network:
    name: thunder-buddy-network
