services:
  app:
    build: .
    container_name: thunder-buddy
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=thunderbuddy
      - DB_PASSWORD=${DB_PASSWORD:-localdev}
      - DB_NAME=thunderbuddy
      - DB_ADMIN_USER=postgres
      - DB_ADMIN_PASSWORD=postgres
      - DATABASE_URL=postgresql://thunderbuddy:${DB_PASSWORD:-localdev}@db:5432/thunderbuddy
      - WEATHERBIT_API_KEY=${WEATHERBIT_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: thunder-buddy-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data:
