version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: thunder-buddy-db
    env_file:
      - ${ENV_FILE:-.env.local}
    environment:
      POSTGRES_DB: ${DB_NAME:-thunderbuddy}
      POSTGRES_USER: ${DB_USERNAME:-thunderbuddy}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-localdev}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: thunder-buddy
    env_file:
      - ${ENV_FILE:-.env.local}
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

volumes:
  postgres_data: 