name: 'Setup Environment'
description: 'Sets up environment variables and configuration'

inputs:
  db_username:
    required: true
    description: 'Database user for authentication and connection'
  db_password:
    required: true
    description: 'Database password for authentication'
  db_host:
    required: true
    description: 'Hostname or IP address of the database server'
  db_port:
    required: true
    description: 'Port number where the database server is listening'
  db_name:
    required: true
    description: 'Name of the database to connect to'
  weatherbit_api_key:
    required: true
    description: 'API key for WeatherBit service authentication'

runs:
  using: "composite"
  steps:
    - name: Create Environment File
      shell: bash
      run: |
        cat > .env << EOL
        DATABASE_URL=postgresql://${{ inputs.db_username }}:${{ inputs.db_password }}@${{ inputs.db_host }}:${{ inputs.db_port }}/${{ inputs.db_name }}
        DB_HOST=${{ inputs.db_host }}
        DB_PORT=${{ inputs.db_port }}
        DB_NAME=${{ inputs.db_name }}
        DB_USERNAME=${{ inputs.db_username }}
        DB_PASSWORD=${{ inputs.db_password }}
        FLASK_DEBUG=false
        REQUEST_TIMEOUT=30
        WEATHERBIT_API_KEY=${{ inputs.weatherbit_api_key }}
        EOL 