---
name: "Docker Build and Push"
description: "Builds and pushes Docker image to registry"

inputs:
  docker_username:
    required: true
    description: "Docker Hub username for authentication and image tagging"
  docker_password:
    required: true
    description: "Docker Hub password or access token for authentication"
  image_name:
    required: true
    description: "Name of the Docker image to build and push (without username prefix)"
  push:
    required: false
    description: "Whether to push the image to registry"
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: inputs.push == 'true'
      shell: bash
      run: |
        echo "${{ inputs.docker_password }}" | docker login --username ${{ inputs.docker_username }} --password-stdin

    - name: Build and Push
      shell: bash
      run: |
        if [[ "${{ inputs.push }}" == "true" ]]; then
          # For production: build multi-arch and push
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg ENV_FILE=.env \
            -t ${{ inputs.docker_username }}/${{ inputs.image_name }}:latest \
            --push \
            .
        else
          # For testing: build single arch and load
          docker buildx build \
            --platform linux/amd64 \
            --build-arg ENV_FILE=.env \
            -t ${{ inputs.docker_username }}/${{ inputs.image_name }}:latest \
            --load \
            .
        fi
