---
name: 'Docker Build and Push'
description: 'Builds and pushes Docker image to registry'

inputs:
  docker_username:
    required: true
    description: 'Docker Hub username for authentication and image tagging'
  docker_password:
    required: true
    description: 'Docker Hub password or access token for authentication'
  image_name:
    required: true
    description: 'Name of the Docker image to build and push (without username prefix)'

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      shell: bash
      run: |
        echo "${{ inputs.docker_password }}" | docker login --username ${{ inputs.docker_username }} --password-stdin

    - name: Build Docker Image
      shell: bash
      run: |
        docker build \
          --build-arg ENV_FILE=.env \
          -t ${{ inputs.image_name }} .

    - name: Tag Docker Image
      shell: bash
      run: |
        docker tag ${{ inputs.image_name }}:latest ${{ inputs.docker_username }}/${{ inputs.image_name }}:latest

    - name: Push Docker Image
      shell: bash
      run: |
        docker push ${{ inputs.docker_username }}/${{ inputs.image_name }}:latest
