---
name: Generate Swagger Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyYAML==6.0.1  # Ensure PyYAML is installed

      - name: Create .env.local for Swagger generation
        run: |
          echo "FLASK_HOST=0.0.0.0" > .env.local
          echo "FLASK_PORT=5000" >> .env.local
          echo "FLASK_DEBUG=False" >> .env.local
          echo "WEATHERBIT_API_KEY=placeholder" >> .env.local
          echo "DB_HOST=localhost" >> .env.local
          echo "DB_PORT=5432" >> .env.local
          echo "DB_NAME=thunder_buddy" >> .env.local
          echo "DB_USERNAME=postgres" >> .env.local
          echo "DB_PASSWORD=placeholder" >> .env.local

      - name: Generate Swagger documentation
        run: make swagger

      - name: Commit and push if changes
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add static/swagger.yaml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update Swagger documentation" && git push)

      - name: Upload Swagger as artifact for PR
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: swagger-docs
          path: static/swagger.yaml
          retention-days: 7
